feat(apps/prod/tekton/configs/pipelines): update pipeline `pingcap-release-ga`
put the shell script in to ci.git and call it.

Signed-off-by: wuhuizuo <wuhuizuo@126.com>

diff --git a/apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml b/apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
--- a/apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
+++ b/apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
@@ -31,81 +31,19 @@ spec:
             image: ghcr.io/pingcap-qe/cd/utils/release:v20231216-101-ge3815f8
             script: |
               #! /usr/bin/env bash
-
               set -ex
-              registry="hub.pingcap.net"
+
               rc_ver="$(params.rc-version)"
               ga_ver="$(params.ga-version)"
+              registry="hub.pingcap.net"
 
-              # TODO: gen it in a script.
-              # For tiup pkgs
-              echo "🚀 Prepare for tiup packages..."
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/tidb/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/tidb/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/tidb/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/tidb/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ctl/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/ctl/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ctl/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/ctl/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ctl/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/ctl/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ctl/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/ctl/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/monitoring/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/monitoring/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/monitoring/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/monitoring/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/monitoring/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/monitoring/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/monitoring/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/monitoring/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ng-monitoring/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/ng-monitoring/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ng-monitoring/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/ng-monitoring/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ng-monitoring/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/ng-monitoring/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ng-monitoring/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/ng-monitoring/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-binlog/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/tidb-binlog/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-binlog/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/tidb-binlog/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-binlog/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/tidb-binlog/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-binlog/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/tidb-binlog/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/tidb-dashboard/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflash/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/tiflash/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflash/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/tiflash/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflash/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/tiflash/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflash/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/tiflash/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/package:${rc_ver}_linux_amd64 && oras tag $registry/pingcap/tiflow/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/package:${rc_ver}_linux_arm64 && oras tag $registry/pingcap/tiflow/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/package:${rc_ver}_darwin_amd64 && oras tag $registry/pingcap/tiflow/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/package:${rc_ver}_darwin_arm64 && oras tag $registry/pingcap/tiflow/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/pd/package:${rc_ver}_linux_amd64 && oras tag $registry/tikv/pd/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/pd/package:${rc_ver}_linux_arm64 && oras tag $registry/tikv/pd/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/pd/package:${rc_ver}_darwin_amd64 && oras tag $registry/tikv/pd/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/pd/package:${rc_ver}_darwin_arm64 && oras tag $registry/tikv/pd/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/tikv/package:${rc_ver}_linux_amd64 && oras tag $registry/tikv/tikv/package:${rc_ver}_linux_amd64 ${ga_ver}_linux_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/tikv/package:${rc_ver}_linux_arm64 && oras tag $registry/tikv/tikv/package:${rc_ver}_linux_arm64 ${ga_ver}_linux_arm64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/tikv/package:${rc_ver}_darwin_amd64 && oras tag $registry/tikv/tikv/package:${rc_ver}_darwin_amd64 ${ga_ver}_darwin_amd64
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/tikv/package:${rc_ver}_darwin_arm64 && oras tag $registry/tikv/tikv/package:${rc_ver}_darwin_arm64 ${ga_ver}_darwin_arm64
+              wget -c --tries=3 https://github.com/PingCAP-QE/ci/raw/main/scripts/artifacts/tag-rc2ga-on-repos.sh
+              chmod +x tag-rc2ga-on-repos.sh
 
-              # for images
-              echo "🚀 Prepare for images..."
-              # community
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/br:${rc_ver} && oras tag $registry/pingcap/tidb/images/br:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/dumpling:${rc_ver} && oras tag $registry/pingcap/tidb/images/dumpling:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/tidb-lightning:${rc_ver} && oras tag $registry/pingcap/tidb/images/tidb-lightning:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/tidb-server:${rc_ver} && oras tag $registry/pingcap/tidb/images/tidb-server:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/monitoring/image:${rc_ver} && oras tag $registry/pingcap/monitoring/image:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/ng-monitoring/image:${rc_ver} && oras tag $registry/pingcap/ng-monitoring/image:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-binlog/image:${rc_ver} && oras tag $registry/pingcap/tidb-binlog/image:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb-dashboard/image:${rc_ver} && oras tag $registry/pingcap/tidb-dashboard/image:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflash/image:${rc_ver} && oras tag $registry/pingcap/tiflash/image:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/images/cdc:${rc_ver} && oras tag $registry/pingcap/tiflow/images/cdc:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/images/dm:${rc_ver} && oras tag $registry/pingcap/tiflow/images/dm:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflow/images/tiflow:${rc_ver} && oras tag $registry/pingcap/tiflow/images/tiflow:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/pd/image:${rc_ver} && oras tag $registry/tikv/pd/image:${rc_ver} ${ga_ver}
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/tikv/image:${rc_ver} && oras tag $registry/tikv/tikv/image:${rc_ver} ${ga_ver}
-              # enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/br:${rc_ver}-enterprise && oras tag $registry/pingcap/tidb/images/br:${rc_ver}-enterprise ${ga_ver}-enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/dumpling:${rc_ver}-enterprise && oras tag $registry/pingcap/tidb/images/dumpling:${rc_ver}-enterprise ${ga_ver}-enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/tidb-lightning:${rc_ver}-enterprise && oras tag $registry/pingcap/tidb/images/tidb-lightning:${rc_ver}-enterprise ${ga_ver}-enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tidb/images/tidb-server:${rc_ver}-enterprise && oras tag $registry/pingcap/tidb/images/tidb-server:${rc_ver}-enterprise ${ga_ver}-enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/pingcap/tiflash/image:${rc_ver}-enterprise && oras tag $registry/pingcap/tiflash/image:${rc_ver}-enterprise ${ga_ver}-enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/pd/image:${rc_ver}-enterprise && oras tag $registry/tikv/pd/image:${rc_ver}-enterprise ${ga_ver}-enterprise
-              oras discover --distribution-spec v1.1-referrers-tag $registry/tikv/tikv/image:${rc_ver}-enterprise && oras tag $registry/tikv/tikv/image:${rc_ver}-enterprise ${ga_ver}-enterprise
+              # force add the tag on repos:
+              # ./tag-rc2ga-on-repos.sh "$rc_ver" "$ga_ver" "$registry" true
+              ./tag-rc2ga-on-repos.sh "$rc_ver" "$ga_ver" "$registry"
+
     - name: wait-tiup-delivery
       runAfter:
         - "ga-tag-oci-artifacts"
@@ -124,6 +62,7 @@ spec:
           - name: wait
             image: ghcr.io/pingcap-qe/cd/utils/release:v20231216-101-ge3815f8
             workingDir: /workspace
+            timeout: 30m0s
             script: |
               #! /usr/bin/env bash
               set -exo pipefail
@@ -139,95 +78,29 @@ spec:
               export PATH=$bin_dir:$PATH
               which tiup
 
-              tiup_mirror="http://tiup.pingcap.net:8987"
               tiup_check_ver="$(params.ga-version)"
+              tiup_mirror="http://tiup.pingcap.net:8987"
+              oci_registry="hub.pingcap.net"
+
               # set mirror, Product is http://tiup.pingcap.net:8987, Staging is http://tiup.pingcap.net:8988
               tiup mirror set $tiup_mirror
 
               # check the tiup pkgs
-              VERSION="$tiup_check_ver"
-              failure=0
+              wget --tries 3 -c -O check-tiup.sh https://github.com/PingCAP-QE/ci/raw/main/scripts/artifacts/check-tiup.sh
+              chmod +x check-tiup.sh
 
-              function record_failure() {
-                  if [ "$1" -eq 0 ]; then
-                      echo "✅ success"
-                  else
-                      echo "❌ failure"
-                      failure=1
-                  fi
-              }
+              while true; do
+                if ./check-tiup.sh "$tiup_check_ver" "$tiup_mirror" "$oci_registry" true; then
+                  echo "🏅🏅🏅 Check TiUP package delivery succeeded!"
+                  break
+                else
+                  echo "Command failed, retrying in 1 minute..."
+                  sleep 60
+                fi
+              done
 
-              function gather_results() {
-                  : >results.yaml
+              cat results.yaml || true
 
-                  # check tiup
-                  for com in 'br' 'cdc' 'ctl' 'dm-master' 'dm-worker' 'dmctl' 'drainer' 'dumpling' 'grafana' 'grafana' 'pd' 'pd-recover' 'prometheus' 'prometheus' 'pump' 'tidb' 'tidb-lightning' 'tiflash' 'tikv' 'tidb-dashboard'; do
-                      echo "🚧 check tiup $com:$VERSION"
-                      platforms=$(tiup list $com | grep -E "^$VERSION\b\s+")
-                      echo $platforms
-                      echo $platforms | grep "darwin/amd64" | grep "darwin/arm64" | grep "linux/amd64" | grep -q "linux/arm64"
-                      record_failure $?
-                      publish_time=$(echo "$platforms" | awk '{print $2}')
-                      yq -i ".tiup[\"${com}\"].published = \"$publish_time\"" results.yaml
-                  done
-
-                  # record tiup built git-sha
-                  for source_oci_pkg_repo in \
-                      pingcap/ctl/package \
-                      pingcap/monitoring/package \
-                      pingcap/ng-monitoring/package \
-                      pingcap/tidb-binlog/package \
-                      pingcap/tidb-dashboard/package \
-                      pingcap/tidb/package \
-                      pingcap/tiflash/package \
-                      pingcap/tiflow/package \
-                      tikv/pd/package \
-                      tikv/tikv/package; do
-                      for platform in linux_amd64 linux_arm64 darwin_amd64 darwin_arm64; do
-                          repo="hub.pingcap.net/${source_oci_pkg_repo}:${VERSION}_${platform}"
-                          oras manifest fetch-config $repo >tmp-oci-artifact-config.yaml
-                          yq '.["net.pingcap.tibuild.git-sha"]' tmp-oci-artifact-config.yaml
-                          git_sha=$(yq .'["net.pingcap.tibuild.git-sha"]' tmp-oci-artifact-config.yaml)
-                          oci_published_at=$(oras manifest fetch $repo | yq '.annotations["org.opencontainers.image.created"]')
-                          for f in $(yq '.["net.pingcap.tibuild.tiup"][].file' tmp-oci-artifact-config.yaml); do
-                              tiup_pkg_name="${f%-v*}"
-                              yq -i ".tiup[\"${tiup_pkg_name}\"].git_sha[\"${platform}\"] = \"$git_sha\"" results.yaml
-                              yq -i ".tiup[\"${tiup_pkg_name}\"].oci_published[\"${platform}\"] = \"$oci_published_at\"" results.yaml
-                          done
-                          rm -rf tmp-oci-artifact-config.yaml
-                      done
-                  done
-              }
-
-              ##### check the results files
-              function check_results() {
-                  # check tiup git_sha and published time
-                  for pkg in $(yq '.tiup | keys | .[]' results.yaml); do
-                      echo "🚧 check tiup built on git-sha for $pkg ..."
-                      yq -e ".tiup[\"$pkg\"].git_sha | map(.) | unique | length == 1" results.yaml
-                      record_failure $?
-
-                      echo "🚧 check tiup published time for $pkg ..."
-                      yq -e ".tiup[\"$pkg\"].published > (.tiup[\"$pkg\"].oci_published | map(.) | sort | .[0])" results.yaml
-                      record_failure $?
-                  done
-              }
-
-              function main() {
-                  gather_results && check_results
-
-                  if [ $failure -eq 0 ]; then
-                      echo '======='
-                      echo "check success"
-                      exit 0
-                  else
-                      echo '======='
-                      echo "check failure"
-                      exit 1
-                  fi
-              }
-
-              main
     - name: compose-offline-pkgs-amd64-community
       runAfter: [wait-tiup-delivery]
       taskRef: { name: pingcap-compose-offline-pkgs }
